run:
	python3 manage.py runserver
activate:
	source venv/bin/activate
migrations:
	python manage.py makemigrations 
migrate:
	python manage.py migrate
content:
	python manage.py migrate content zero
superuser:
	python manage.py createsuperuser